/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

#include <a_samp>

new PlayerText:Logo[MAX_PLAYERS];
new PlayerText:Logo2[MAX_PLAYERS];
new PlayerText:Char1[MAX_PLAYERS];
new PlayerText:Char2[MAX_PLAYERS];
new PlayerText:Char3[MAX_PLAYERS];
new PlayerText:Logo3[MAX_PLAYERS];
new PlayerText:CharName1[MAX_PLAYERS];
new PlayerText:CharName2[MAX_PLAYERS];
new PlayerText:CharName3[MAX_PLAYERS];
new PlayerText:textdraw_9[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	Logo[playerid] = CreatePlayerTextDraw(playerid, 424.000000, 163.000000, "Angeles City");
	PlayerTextDrawFont(playerid, Logo[playerid], 0);
	PlayerTextDrawLetterSize(playerid, Logo[playerid], 1.516667, 4.599997);
	PlayerTextDrawTextSize(playerid, Logo[playerid], 299.000000, 27.000000);
	PlayerTextDrawSetOutline(playerid, Logo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Logo[playerid], 0);
	PlayerTextDrawAlignment(playerid, Logo[playerid], 1);
	PlayerTextDrawColor(playerid, Logo[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, Logo[playerid], -1378294017);
	PlayerTextDrawBoxColor(playerid, Logo[playerid], 50);
	PlayerTextDrawUseBox(playerid, Logo[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Logo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Logo[playerid], 0);

	Logo2[playerid] = CreatePlayerTextDraw(playerid, 541.000000, 209.000000, "Role Play Game");
	PlayerTextDrawFont(playerid, Logo2[playerid], 0);
	PlayerTextDrawLetterSize(playerid, Logo2[playerid], 0.766666, 3.099999);
	PlayerTextDrawTextSize(playerid, Logo2[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Logo2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Logo2[playerid], 1);
	PlayerTextDrawAlignment(playerid, Logo2[playerid], 2);
	PlayerTextDrawColor(playerid, Logo2[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, Logo2[playerid], -1378294017);
	PlayerTextDrawBoxColor(playerid, Logo2[playerid], 50);
	PlayerTextDrawUseBox(playerid, Logo2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Logo2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Logo2[playerid], 0);

	Char1[playerid] = CreatePlayerTextDraw(playerid, 283.000000, 288.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, Char1[playerid], 5);
	PlayerTextDrawLetterSize(playerid, Char1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Char1[playerid], 135.000000, 109.500000);
	PlayerTextDrawSetOutline(playerid, Char1[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Char1[playerid], 0);
	PlayerTextDrawAlignment(playerid, Char1[playerid], 1);
	PlayerTextDrawColor(playerid, Char1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Char1[playerid], -1378294147);
	PlayerTextDrawBoxColor(playerid, Char1[playerid], 255);
	PlayerTextDrawUseBox(playerid, Char1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Char1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Char1[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, Char1[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, Char1[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, Char1[playerid], 1, 1);

	Char2[playerid] = CreatePlayerTextDraw(playerid, 284.000000, 62.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, Char2[playerid], 5);
	PlayerTextDrawLetterSize(playerid, Char2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Char2[playerid], 135.000000, 109.500000);
	PlayerTextDrawSetOutline(playerid, Char2[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Char2[playerid], 0);
	PlayerTextDrawAlignment(playerid, Char2[playerid], 1);
	PlayerTextDrawColor(playerid, Char2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Char2[playerid], -1378294147);
	PlayerTextDrawBoxColor(playerid, Char2[playerid], 255);
	PlayerTextDrawUseBox(playerid, Char2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Char2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Char2[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, Char2[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, Char2[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, Char2[playerid], 1, 1);

	Char3[playerid] = CreatePlayerTextDraw(playerid, 283.000000, 175.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, Char3[playerid], 5);
	PlayerTextDrawLetterSize(playerid, Char3[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Char3[playerid], 135.000000, 109.500000);
	PlayerTextDrawSetOutline(playerid, Char3[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Char3[playerid], 0);
	PlayerTextDrawAlignment(playerid, Char3[playerid], 1);
	PlayerTextDrawColor(playerid, Char3[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Char3[playerid], -1378294147);
	PlayerTextDrawBoxColor(playerid, Char3[playerid], 255);
	PlayerTextDrawUseBox(playerid, Char3[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Char3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Char3[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, Char3[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, Char3[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, Char3[playerid], 1, 1);

	Logo3[playerid] = CreatePlayerTextDraw(playerid, 178.000000, 149.000000, "Character Menu");
	PlayerTextDrawFont(playerid, Logo3[playerid], 1);
	PlayerTextDrawLetterSize(playerid, Logo3[playerid], 1.304166, 6.499999);
	PlayerTextDrawTextSize(playerid, Logo3[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Logo3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Logo3[playerid], 0);
	PlayerTextDrawAlignment(playerid, Logo3[playerid], 2);
	PlayerTextDrawColor(playerid, Logo3[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, Logo3[playerid], -1378294017);
	PlayerTextDrawBoxColor(playerid, Logo3[playerid], 50);
	PlayerTextDrawUseBox(playerid, Logo3[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Logo3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Logo3[playerid], 0);

	CharName1[playerid] = CreatePlayerTextDraw(playerid, 347.000000, 48.000000, "Char Name");
	PlayerTextDrawFont(playerid, CharName1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, CharName1[playerid], 0.404166, 1.750000);
	PlayerTextDrawTextSize(playerid, CharName1[playerid], -8.500000, 142.500000);
	PlayerTextDrawSetOutline(playerid, CharName1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, CharName1[playerid], 0);
	PlayerTextDrawAlignment(playerid, CharName1[playerid], 2);
	PlayerTextDrawColor(playerid, CharName1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, CharName1[playerid], -1061109505);
	PlayerTextDrawBoxColor(playerid, CharName1[playerid], 200);
	PlayerTextDrawUseBox(playerid, CharName1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, CharName1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, CharName1[playerid], 1);

	CharName2[playerid] = CreatePlayerTextDraw(playerid, 350.000000, 168.000000, "Char Name");
	PlayerTextDrawFont(playerid, CharName2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, CharName2[playerid], 0.404166, 1.750000);
	PlayerTextDrawTextSize(playerid, CharName2[playerid], -8.500000, 142.500000);
	PlayerTextDrawSetOutline(playerid, CharName2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, CharName2[playerid], 0);
	PlayerTextDrawAlignment(playerid, CharName2[playerid], 2);
	PlayerTextDrawColor(playerid, CharName2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, CharName2[playerid], -1061109505);
	PlayerTextDrawBoxColor(playerid, CharName2[playerid], 200);
	PlayerTextDrawUseBox(playerid, CharName2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, CharName2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, CharName2[playerid], 1);

	CharName3[playerid] = CreatePlayerTextDraw(playerid, 350.000000, 283.000000, "Char Name");
	PlayerTextDrawFont(playerid, CharName3[playerid], 1);
	PlayerTextDrawLetterSize(playerid, CharName3[playerid], 0.404166, 1.750000);
	PlayerTextDrawTextSize(playerid, CharName3[playerid], -8.500000, 142.500000);
	PlayerTextDrawSetOutline(playerid, CharName3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, CharName3[playerid], 0);
	PlayerTextDrawAlignment(playerid, CharName3[playerid], 2);
	PlayerTextDrawColor(playerid, CharName3[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, CharName3[playerid], -1061109505);
	PlayerTextDrawBoxColor(playerid, CharName3[playerid], 200);
	PlayerTextDrawUseBox(playerid, CharName3[playerid], 0);
	PlayerTextDrawSetProportional(playerid, CharName3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, CharName3[playerid], 1);

	textdraw_9[playerid] = CreatePlayerTextDraw(playerid, 216.000000, 5.000000, "Web:gtaip.com");
	PlayerTextDrawFont(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_9[playerid], 1.054166, 4.099998);
	PlayerTextDrawTextSize(playerid, textdraw_9[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_9[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawColor(playerid, textdraw_9[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, textdraw_9[playerid], -1378294017);
	PlayerTextDrawBoxColor(playerid, textdraw_9[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_9[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_9[playerid], 0);

	return 1;
}

public OnPlayerDisconnect(playerid)
{
	PlayerTextDrawDestroy(playerid, Logo[playerid]);
	PlayerTextDrawDestroy(playerid, Logo2[playerid]);
	PlayerTextDrawDestroy(playerid, Char1[playerid]);
	PlayerTextDrawDestroy(playerid, Char2[playerid]);
	PlayerTextDrawDestroy(playerid, Char3[playerid]);
	PlayerTextDrawDestroy(playerid, Logo3[playerid]);
	PlayerTextDrawDestroy(playerid, CharName1[playerid]);
	PlayerTextDrawDestroy(playerid, CharName2[playerid]);
	PlayerTextDrawDestroy(playerid, CharName3[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_9[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, Logo[playerid]);
		PlayerTextDrawShow(playerid, Logo2[playerid]);
		PlayerTextDrawShow(playerid, Char1[playerid]);
		PlayerTextDrawShow(playerid, Char2[playerid]);
		PlayerTextDrawShow(playerid, Char3[playerid]);
		PlayerTextDrawShow(playerid, Logo3[playerid]);
		PlayerTextDrawShow(playerid, CharName1[playerid]);
		PlayerTextDrawShow(playerid, CharName2[playerid]);
		PlayerTextDrawShow(playerid, CharName3[playerid]);
		PlayerTextDrawShow(playerid, textdraw_9[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
